[project]
name = "kws-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "torch>=2.0.0",
    "torchaudio",
    "torchcodec",
    "python-multipart",	
    "uvicorn",
    "pandas",
    "numpy",
    "nnAudio",
    "paho-mqtt",
    "requests",
    "dotenv",
]
